name: Manual Integration Tests

on:
  workflow_dispatch:
    inputs:
      dockerhub_username:
        description: 'Docker Hub Username'
        required: true
      dockerhub_token:
        description: 'Docker Hub Access Token'
        required: true

jobs:
  test-integration-scenarios:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Test Login to Docker Hub
        uses: ./
        with:
          username: ${{ github.event.inputs.dockerhub_username }}
          password: ${{ github.event.inputs.dockerhub_token }}

      - name: Verify Docker Hub Login
        run: |
          docker info | grep "Username"
          echo "✅ Docker Hub login successful!"

      - name: Test Login to GitHub Container Registry
        uses: ./
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify GHCR Login
        run: |
          docker info | grep "ghcr.io"
          echo "✅ GHCR login successful!"